// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL3N4vzo6pcnP86l0xBQb47fjRR-569LI',
    appId: '1:892734924327:web:78bc55a08115bd0fca1002',
    messagingSenderId: '892734924327',
    projectId: 'assistant-baca9',
    authDomain: 'assistant-baca9.firebaseapp.com',
    storageBucket: 'assistant-baca9.appspot.com',
    measurementId: 'G-Z90TLCXJYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvYsUvIU_BC3OZA9MKk8cNrcFPmxWkyZc',
    appId: '1:892734924327:android:8e2841d43698457cca1002',
    messagingSenderId: '892734924327',
    projectId: 'assistant-baca9',
    storageBucket: 'assistant-baca9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdWG5myGVEC7i_IBnHFrLwywFqZlzgvRg',
    appId: '1:892734924327:ios:7d278ec81649d8a6ca1002',
    messagingSenderId: '892734924327',
    projectId: 'assistant-baca9',
    storageBucket: 'assistant-baca9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdWG5myGVEC7i_IBnHFrLwywFqZlzgvRg',
    appId: '1:892734924327:ios:7d278ec81649d8a6ca1002',
    messagingSenderId: '892734924327',
    projectId: 'assistant-baca9',
    storageBucket: 'assistant-baca9.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL3N4vzo6pcnP86l0xBQb47fjRR-569LI',
    appId: '1:892734924327:web:6877d52ecacb5a5cca1002',
    messagingSenderId: '892734924327',
    projectId: 'assistant-baca9',
    authDomain: 'assistant-baca9.firebaseapp.com',
    storageBucket: 'assistant-baca9.appspot.com',
    measurementId: 'G-YX7C0YTWJM',
  );
}
